/* eslint-disable @typescript-eslint/no-unused-vars */
"use client";

import { useActionState, useMemo, useState } from "react";
import { Copy, Plus, Sparkles, Trash2 } from "lucide-react";
import { useForm } from "react-hook-form";
import { createWorkOrder } from "@/actions/work-orders";
import type { ActionState } from "@/actions/types";
import { Button } from "@/components/ui/button";
import { Card } from "@/components/ui/card";
import { Input, Label, Select, Textarea } from "@/components/ui/field";
import { SubmitButton } from "@/components/ui/submit-button";
import { parseTaskLines, TRADE_CATEGORIES, UNITS } from "@/lib/domain";
import { calculateGst, toCents } from "@/lib/utils";

type TaskDraft = { id: string; trade: string; area: string; description: string; quantity: number; unit: string; unitRate: string };
type HeaderFields = { clientName: string; workOrderNumber: string; streetAddress: string; suburb: string; postcode: string };
const makeTask = (): TaskDraft => ({ id: crypto.randomUUID(), trade: "Painting", area: "", description: "", quantity: 1, unit: "ea", unitRate: "" });

export function WorkOrderForm() {
  const [state, action] = useActionState(createWorkOrder, {} as ActionState);
  const { register } = useForm<HeaderFields>();
  const [tasks, setTasks] = useState<TaskDraft[]>([makeTask()]);
  const [paste, setPaste] = useState("");
  const [showPaste, setShowPaste] = useState(false);
  const [subtotal, setSubtotal] = useState("2000.00");
  const [gstRate, setGstRate] = useState("0.10");
  const money = useMemo(() => calculateGst(toCents(subtotal) ?? 0, Number(gstRate) || 0), [subtotal, gstRate]);
  const updateTask = (id: string, patch: Partial<TaskDraft>) => setTasks((current) => current.map((task) => task.id === id ? { ...task, ...patch } : task));
  const importTasks = () => {
    const parsed = parseTaskLines(paste);
    if (parsed.length) setTasks(parsed.map((task) => ({ id: crypto.randomUUID(), trade: String(task.trade), area: String(task.area ?? ""), description: String(task.description), quantity: Number(task.quantity), unit: String(task.unit), unitRate: "" })));
    setShowPaste(false);
  };
  return <form action={action} className="space-y-6">
    {state.error && <div role="alert" className="rounded-2xl border border-[#e7c8c4] bg-[#f8e7e4] px-4 py-3 text-sm font-medium text-[#8b3730]">{state.error}</div>}
    <Card className="p-5 sm:p-6"><div className="mb-5"><p className="text-xs font-bold uppercase tracking-[.14em] text-[#a46327]">1 · Client and site</p><h2 className="mt-1 text-xl font-semibold">Who issued the work, and where is it?</h2></div><div className="grid gap-4 sm:grid-cols-2 lg:grid-cols-3"><div><Label htmlFor="clientName">Client (principal)</Label><Input id="clientName" {...register("clientName", { required: true })} placeholder="Bentino Pty Ltd" /></div><div><Label htmlFor="customerName">Customer / occupant <span className="font-normal text-[#89918e]">optional</span></Label><Input id="customerName" name="customerName" placeholder="Francesco Amato" /></div><div><Label htmlFor="customerPhone">Customer phone</Label><Input id="customerPhone" name="customerPhone" type="tel" /></div><div className="sm:col-span-2"><Label htmlFor="streetAddress">Site address</Label><Input id="streetAddress" {...register("streetAddress", { required: true })} placeholder="4 Irwan St" /></div><div><Label htmlFor="suburb">Suburb</Label><Input id="suburb" {...register("suburb", { required: true })} placeholder="Saratoga" /></div><div><Label htmlFor="state">State</Label><Select id="state" name="state" defaultValue="NSW">{["NSW","ACT","VIC","QLD","SA","WA","TAS","NT"].map((state) => <option key={state}>{state}</option>)}</Select></div><div><Label htmlFor="postcode">Postcode</Label><Input id="postcode" {...register("postcode", { required: true, pattern: /\d{4}/ })} inputMode="numeric" maxLength={4} /></div><div><Label htmlFor="siteContactName">Site contact</Label><Input id="siteContactName" name="siteContactName" /></div><div><Label htmlFor="siteContactPhone">Site contact phone</Label><Input id="siteContactPhone" name="siteContactPhone" type="tel" /></div></div></Card>
    <Card className="p-5 sm:p-6"><div className="mb-5"><p className="text-xs font-bold uppercase tracking-[.14em] text-[#a46327]">2 · Order details</p><h2 className="mt-1 text-xl font-semibold">Reference and timing</h2></div><div className="grid gap-4 sm:grid-cols-2 lg:grid-cols-3"><div><Label htmlFor="workOrderNumber">Work order number</Label><Input id="workOrderNumber" {...register("workOrderNumber", { required: true })} placeholder="20299-29572" /></div><div><Label htmlFor="jobNumber">Job number</Label><Input id="jobNumber" name="jobNumber" /></div><div><Label htmlFor="clientReference">Client reference</Label><Input id="clientReference" name="clientReference" /></div><div><Label htmlFor="supervisorName">Client supervisor</Label><Input id="supervisorName" name="supervisorName" /></div><div><Label htmlFor="supervisorPhone">Supervisor phone</Label><Input id="supervisorPhone" name="supervisorPhone" type="tel" /></div><div><Label htmlFor="issuedAt">Issued</Label><Input id="issuedAt" name="issuedAt" type="date" /></div><div><Label htmlFor="startDate">Start date</Label><Input id="startDate" name="startDate" type="date" /></div><div><Label htmlFor="dueDate">Completion due</Label><Input id="dueDate" name="dueDate" type="date" /></div><div className="sm:col-span-2 lg:col-span-3"><Label htmlFor="additionalInstructions">Site instructions <span className="font-normal text-[#89918e]">visible to assigned workers</span></Label><Textarea id="additionalInstructions" name="additionalInstructions" placeholder="Access, parking, safety and on-site instructions" /></div><div className="sm:col-span-2 lg:col-span-3"><Label htmlFor="notes">Internal notes</Label><Textarea id="notes" name="notes" /></div></div></Card>
    <Card className="overflow-hidden"><div className="flex flex-col justify-between gap-3 border-b border-[#e7e3da] p-5 sm:flex-row sm:items-center sm:px-6"><div><p className="text-xs font-bold uppercase tracking-[.14em] text-[#a46327]">3 · Scope</p><h2 className="mt-1 text-xl font-semibold">Trade-grouped tasks</h2></div><Button type="button" variant="secondary" onClick={() => setShowPaste((value) => !value)}><Sparkles className="h-4 w-4" />Paste from PDF text</Button></div>{showPaste && <div className="border-b border-[#e7e3da] bg-[#f8f6f1] p-5 sm:p-6"><Label htmlFor="pasteTasks">Paste task lines</Label><Textarea id="pasteTasks" value={paste} onChange={(event) => setPaste(event.target.value)} placeholder={'Painting\nPrepare and paint walls 45/m2\nPrepare and paint skirting 20/lm'} /><p className="mt-2 text-xs text-[#77817e]">Recognises trade headers and lines ending in quantity/unit. The word “Material” is ignored.</p><Button type="button" className="mt-3" onClick={importTasks}>Import recognised tasks</Button></div>}<input type="hidden" name="tasks" value={JSON.stringify(tasks.map(({ id: _id, ...task }) => task))} />
    <div className="divide-y divide-[#ebe7df]">{tasks.map((task, index) => <div key={task.id} className="p-5 sm:px-6"><div className="mb-3 flex items-center justify-between"><span className="text-xs font-bold uppercase tracking-wider text-[#8a918e]">Task {index + 1}</span><div className="flex gap-1"><button type="button" title="Duplicate task" className="grid h-9 w-9 place-items-center rounded-lg text-[#697370] hover:bg-[#eeece5]" onClick={() => setTasks((current) => [...current.slice(0,index+1), { ...task, id: crypto.randomUUID() }, ...current.slice(index+1)])}><Copy className="h-4 w-4" /></button><button type="button" title="Remove task" disabled={tasks.length === 1} className="grid h-9 w-9 place-items-center rounded-lg text-[#913a31] hover:bg-[#f5dfdc] disabled:opacity-30" onClick={() => setTasks((current) => current.filter((item) => item.id !== task.id))}><Trash2 className="h-4 w-4" /></button></div></div><div className="grid gap-3 md:grid-cols-[150px_150px_1fr_90px_85px_120px]"><div><Label>Trade</Label><Select value={task.trade} onChange={(e) => updateTask(task.id,{trade:e.target.value})}>{TRADE_CATEGORIES.map((trade) => <option key={trade}>{trade}</option>)}</Select></div><div><Label>Area</Label><Input value={task.area} onChange={(e) => updateTask(task.id,{area:e.target.value})} placeholder="Lounge" /></div><div><Label>Description</Label><Input value={task.description} onChange={(e) => updateTask(task.id,{description:e.target.value})} placeholder="Describe the work" /></div><div><Label>Qty</Label><Input type="number" min="0.001" step="0.001" value={task.quantity} onChange={(e) => updateTask(task.id,{quantity:Number(e.target.value)})} /></div><div><Label>Unit</Label><Select value={task.unit} onChange={(e) => updateTask(task.id,{unit:e.target.value})}>{UNITS.map((unit) => <option key={unit}>{unit}</option>)}</Select></div><div><Label>Rate <span className="font-normal text-[#89918e]">optional</span></Label><Input type="number" min="0" step="0.01" value={task.unitRate} onChange={(e) => updateTask(task.id,{unitRate:e.target.value})} placeholder="$0.00" /></div></div></div>)}</div><div className="p-5 sm:px-6"><Button type="button" variant="secondary" onClick={() => setTasks((current) => [...current, makeTask()])}><Plus className="h-4 w-4" />Add task</Button></div></Card>
    <Card className="p-5 sm:p-6"><div className="mb-5"><p className="text-xs font-bold uppercase tracking-[.14em] text-[#a46327]">4 · Manager-only pricing</p><h2 className="mt-1 text-xl font-semibold">Order total</h2><p className="mt-1 text-sm text-[#77817e]">Stored separately and never returned to worker accounts.</p></div><div className="grid gap-4 sm:grid-cols-3"><div><Label htmlFor="subtotalDisplay">Subtotal</Label><Input id="subtotalDisplay" inputMode="decimal" value={subtotal} onChange={(e) => setSubtotal(e.target.value)} /></div><div><Label htmlFor="gstRate">GST rate</Label><Input id="gstRate" inputMode="decimal" value={gstRate} onChange={(e) => setGstRate(e.target.value)} /></div><div><Label>Total</Label><div className="flex min-h-11 items-center rounded-xl bg-[#e5efed] px-3.5 font-mono font-bold text-[#24575d]">${(money.totalCents / 100).toFixed(2)}</div></div></div><input type="hidden" name="subtotalCents" value={money.subtotalCents} /><input type="hidden" name="gstRate" value={gstRate} /><input type="hidden" name="gstCents" value={money.gstCents} /><input type="hidden" name="totalCents" value={money.totalCents} /><input type="hidden" name="totalOverride" value="true" /><div className="mt-5"><Label htmlFor="duplicateReason">Duplicate reason <span className="font-normal text-[#89918e]">only if this intentionally duplicates an existing order</span></Label><Input id="duplicateReason" name="duplicateReason" /></div></Card>
    <div className="sticky bottom-4 flex items-center justify-between gap-4 rounded-2xl border border-[#d4cec2] bg-[#faf9f6]/95 p-3 shadow-xl backdrop-blur"><p className="hidden text-sm text-[#707a77] sm:block">{tasks.length} task{tasks.length === 1 ? "" : "s"} · ${(money.totalCents/100).toFixed(2)} total</p><SubmitButton className="ml-auto min-w-40" pendingText="Creating order...">Create work order</SubmitButton></div>
  </form>;
}
