/* eslint-disable @next/next/no-img-element */
import { Camera, CheckCircle2, TriangleAlert } from "lucide-react";
import { PageHeader } from "@/components/page-header";
import { ReviewForm } from "@/components/review-form";
import { StatusBadge } from "@/components/status-badge";
import { Card } from "@/components/ui/card";
import { EmptyState } from "@/components/empty-state";
import type { TaskStatus } from "@/lib/domain";
import { createClient } from "@/lib/supabase/server";
import { formatDate } from "@/lib/utils";

type SubmissionRow = { id: number; notes: string | null; cannot_complete: boolean; problem_report: string | null; submitted_at: string; worker: { user_profile: { display_name: string } | null } | null; task: { id: number; description: string; quantity: number; unit: string; status: TaskStatus; work_order: { id: number; work_order_number: string; client: { name: string } | null; site: { suburb: string } | null } | null } | null; completion_photo: Array<{ id: number; width: number | null; height: number | null }> };

export const metadata = { title: "Completion review" };
export default async function ReviewPage() {
  const supabase = await createClient();
  const { data } = await supabase.from("completion_submission").select("id,notes,cannot_complete,problem_report,submitted_at,worker:worker_id(user_profile:user_id(display_name)),task:task_id(id,description,quantity,unit,status,work_order:work_order_id(id,work_order_number,client:client_id(name),site:site_id(suburb))),completion_photo(id,width,height)").eq("status", "submitted").order("submitted_at");
  const submissions = (data ?? []) as unknown as SubmissionRow[];
  return <><PageHeader eyebrow="Quality control" title="Completion review" description="Check worker notes and photo evidence before the task is signed off." />{!submissions.length ? <EmptyState icon={CheckCircle2} title="Review queue is clear" description="New completion submissions will appear here as workers finish their tasks." /> : <div className="grid gap-5 xl:grid-cols-2">{submissions.map((submission) => <Card key={submission.id} className="overflow-hidden"><div className="flex items-start justify-between gap-3 border-b border-[#ebe7df] p-5"><div><p className="text-xs font-bold uppercase tracking-wider text-[#a46327]">{submission.task?.work_order?.work_order_number} · {submission.task?.work_order?.site?.suburb}</p><h2 className="mt-1 text-lg font-semibold">{submission.task?.description}</h2><p className="mt-1 text-sm text-[#707a77]">{submission.task?.quantity} {submission.task?.unit} · {submission.worker?.user_profile?.display_name} · {formatDate(submission.submitted_at, "d MMM, h:mm a")}</p></div>{submission.task?.status && <StatusBadge status={submission.task.status} />}</div><div className="p-5">{submission.cannot_complete && <div className="mb-4 flex gap-3 rounded-xl bg-[#f8e7e4] p-4 text-sm text-[#8b3730]"><TriangleAlert className="h-5 w-5 shrink-0" /><div><p className="font-bold">Worker reported a problem</p><p className="mt-1">{submission.problem_report}</p></div></div>}<div className="rounded-xl bg-[#f8f6f1] p-4"><p className="text-xs font-bold uppercase tracking-wider text-[#818986]">Worker notes</p><p className="mt-2 whitespace-pre-wrap text-sm leading-6">{submission.notes || "No notes added."}</p></div><div className="mt-4"><div className="mb-2 flex items-center gap-2 text-sm font-semibold"><Camera className="h-4 w-4" />{submission.completion_photo.length} photo{submission.completion_photo.length === 1 ? "" : "s"}</div>{submission.completion_photo.length ? <div className="grid grid-cols-3 gap-2">{submission.completion_photo.map((photo) => <a key={photo.id} href={`/api/photos/${photo.id}`} target="_blank" rel="noreferrer" className="grid aspect-square place-items-center overflow-hidden rounded-xl bg-[#e5e3dd]"><img src={`/api/photos/${photo.id}?thumbnail=1`} alt="Completion evidence" className="h-full w-full object-cover" /></a>)}</div> : <div className="rounded-xl border border-dashed border-[#d0cbc0] p-5 text-center text-sm text-[#7a8380]">No photos attached</div>}</div><ReviewForm submissionId={submission.id} /></div></Card>)}</div>}</>;
}
